import type { Metadata } from "next";
import { Nunito, Protest_Riot } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/layout/Navbar";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700", "800"],
  variable: "--font-nunito",
});

const protestRiot = Protest_Riot({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  variable: "--font-protestRiot",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${protestRiot.variable} ${nunito.className} antialiased `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
